#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  cat <<'EOF'
Install Shenleng web pull-agent systemd timer.

Usage:
  scripts/install-web-pull-agent-systemd.sh --manifest-url https://.../manifest.json

Options:
  --project-dir PATH   Default: /home/ecs-user/Projects/shenleng
  --manifest-url URL   Manifest URL generated by the OSS publish workflow
  --public-url URL     Default: https://shenleng.roinland.com

This installs a timer that periodically downloads a manifest, verifies the
artifact sha256, and calls scripts/deploy-web-light.sh. It does not use SSH for
normal deployments after installation.
EOF
}

project_dir="/home/ecs-user/Projects/shenleng"
manifest_url=""
public_url="https://shenleng.roinland.com"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --project-dir)
      project_dir="${2:-}"
      shift 2
      ;;
    --manifest-url)
      manifest_url="${2:-}"
      shift 2
      ;;
    --public-url)
      public_url="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

[ -n "$project_dir" ] || { echo "--project-dir is required" >&2; exit 1; }
[ -n "$manifest_url" ] || { echo "--manifest-url is required" >&2; exit 1; }
[ -d "$project_dir" ] || { echo "project directory not found: $project_dir" >&2; exit 1; }
[ -x "$project_dir/scripts/deploy-web-light.sh" ] || { echo "deploy-web-light.sh not found or not executable" >&2; exit 1; }

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

sudo install -d -m 0755 "$project_dir/scripts"
if [ "$(realpath "$repo_dir/scripts/deploy-web-pull-agent.sh")" != "$(realpath -m "$project_dir/scripts/deploy-web-pull-agent.sh")" ]; then
  sudo install -m 0755 "$repo_dir/scripts/deploy-web-pull-agent.sh" "$project_dir/scripts/deploy-web-pull-agent.sh"
else
  chmod 0755 "$project_dir/scripts/deploy-web-pull-agent.sh"
fi

cat >"$project_dir/.deploy-pull.env.tmp" <<ENV
WEB_DEPLOY_MANIFEST_URL=$manifest_url
PUBLIC_URL=$public_url
PROJECT_DIR=$project_dir
ENV
chmod 600 "$project_dir/.deploy-pull.env.tmp"
mv "$project_dir/.deploy-pull.env.tmp" "$project_dir/.deploy-pull.env"

escape_sed() {
  printf '%s' "$1" | sed 's/[&/\]/\\&/g'
}

project_escaped="$(escape_sed "$project_dir")"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

sed -e "s/{{PROJECT_DIR}}/$project_escaped/g" \
  "$repo_dir/systemd/shenleng-web-pull-agent.service.template" >"$tmp_dir/shenleng-web-pull-agent.service"
cp "$repo_dir/systemd/shenleng-web-pull-agent.timer" "$tmp_dir/shenleng-web-pull-agent.timer"

sudo install -m 0644 "$tmp_dir/shenleng-web-pull-agent.service" /etc/systemd/system/shenleng-web-pull-agent.service
sudo install -m 0644 "$tmp_dir/shenleng-web-pull-agent.timer" /etc/systemd/system/shenleng-web-pull-agent.timer
sudo systemctl daemon-reload
sudo systemctl enable --now shenleng-web-pull-agent.timer >/dev/null

systemctl is-active shenleng-web-pull-agent.timer
echo "Installed pull-agent timer for manifest: $manifest_url"
